import { LocationData } from '../types';

export const PROVINCES_NEPAL = [
  { id: 'all', nameNepali: 'सबै स्थान (All)', nameEnglish: 'All Locations' },
  { id: 'p1', nameNepali: 'कोशी प्रदेश', nameEnglish: 'Koshi Province' },
  { id: 'p2', nameNepali: 'मधेश प्रदेश', nameEnglish: 'Madhesh Province' },
  { id: 'p3', nameNepali: 'बागमती प्रदेश', nameEnglish: 'Bagmati Province' },
  { id: 'p4', nameNepali: 'गण्डकी प्रदेश', nameEnglish: 'Gandaki Province' },
  { id: 'p5', nameNepali: 'लुम्बिनी प्रदेश', nameEnglish: 'Lumbini Province' },
  { id: 'p6', nameNepali: 'कर्णाली प्रदेश', nameEnglish: 'Karnali Province' },
  { id: 'p7', nameNepali: 'सुदूरपश्चिम प्रदेश', nameEnglish: 'Sudurpashchim Province' },
  { id: 'intl', nameNepali: 'अन्तर्राष्ट्रिय (International)', nameEnglish: 'International Diaspora' },
];

export const NEPAL_LOCATIONS: LocationData[] = [
  // -------------------------------------------------------------
  // 1. BAGMATI PROVINCE (बागमती प्रदेश) - Kathmandu Valley & Districts
  // -------------------------------------------------------------
  {
    id: 'kathmandu',
    nameNepali: 'काठमाडौँ (राजधानी)',
    nameEnglish: 'Kathmandu (Capital)',
    province: 'बागमती प्रदेश',
    latitude: 27.7172,
    longitude: 85.3240,
    elevationMeters: 1400,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
    isDefault: true,
  },
  {
    id: 'lalitpur',
    nameNepali: 'ललितपुर (पाटन)',
    nameEnglish: 'Lalitpur (Patan)',
    province: 'बागमती प्रदेश',
    latitude: 27.6710,
    longitude: 85.3218,
    elevationMeters: 1400,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bhaktapur',
    nameNepali: 'भक्तपुर',
    nameEnglish: 'Bhaktapur',
    province: 'बागमती प्रदेश',
    latitude: 27.6710,
    longitude: 85.4298,
    elevationMeters: 1401,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'kavre_dhulikhel',
    nameNepali: 'काभ्रेपलाञ्चोक (धुलिखेल / बनेपा)',
    nameEnglish: 'Kavrepalanchok (Dhulikhel / Banepa)',
    province: 'बागमती प्रदेश',
    latitude: 27.6253,
    longitude: 85.5561,
    elevationMeters: 1550,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sindhupalchok_chautara',
    nameNepali: 'सिन्धुपाल्चोक (चौतारा / मेलम्ची)',
    nameEnglish: 'Sindhupalchok (Chautara / Melamchi)',
    province: 'बागमती प्रदेश',
    latitude: 27.7889,
    longitude: 85.7197,
    elevationMeters: 1600,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dolakha_charikot',
    nameNepali: 'दोलखा (चरीकोट / जिरी)',
    nameEnglish: 'Dolakha (Charikot / Jiri)',
    province: 'बागमती प्रदेश',
    latitude: 27.6714,
    longitude: 86.0333,
    elevationMeters: 1970,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'ramechhap_manthali',
    nameNepali: 'रामेछाप (मन्थली)',
    nameEnglish: 'Ramechhap (Manthali)',
    province: 'बागमती प्रदेश',
    latitude: 27.3833,
    longitude: 86.0667,
    elevationMeters: 474,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sindhuli_madi',
    nameNepali: 'सिन्धुली (सिन्धुलीमाढी)',
    nameEnglish: 'Sindhuli (Kamalamai / Sindhulimadhi)',
    province: 'बागमती प्रदेश',
    latitude: 27.2472,
    longitude: 85.9189,
    elevationMeters: 546,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'makwanpur_hetauda',
    nameNepali: 'मकवानपुर (हेटौँडा - प्रादेशिक राजधानी)',
    nameEnglish: 'Makwanpur (Hetauda - Province Capital)',
    province: 'बागमती प्रदेश',
    latitude: 27.4289,
    longitude: 85.0322,
    elevationMeters: 390,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'chitwan_bharatpur',
    nameNepali: 'चितवन (भरतपुर / नारायणगढ)',
    nameEnglish: 'Chitwan (Bharatpur / Narayangarh)',
    province: 'बागमती प्रदेश',
    latitude: 27.6833,
    longitude: 84.4333,
    elevationMeters: 208,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dhading_besi',
    nameNepali: 'धादिङ (धादिङबेसी)',
    nameEnglish: 'Dhading (Dhading Besi)',
    province: 'बागमती प्रदेश',
    latitude: 27.8667,
    longitude: 84.9000,
    elevationMeters: 600,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'nuwakot_bidur',
    nameNepali: 'नुवाकोट (विदुर / त्रिशूली)',
    nameEnglish: 'Nuwakot (Bidur / Trishuli)',
    province: 'बागमती प्रदेश',
    latitude: 27.9167,
    longitude: 85.1667,
    elevationMeters: 630,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'rasuwa_dhunche',
    nameNepali: 'रसुवा (धुन्चे / स्याफ्रुबेसी)',
    nameEnglish: 'Rasuwa (Dhunche / Syabrubesi)',
    province: 'बागमती प्रदेश',
    latitude: 28.1167,
    longitude: 85.3000,
    elevationMeters: 1960,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 2. KOSHI PROVINCE (कोशी प्रदेश) - 14 Districts & Key Towns
  // -------------------------------------------------------------
  {
    id: 'morang_biratnagar',
    nameNepali: 'विराटनगर (मोरङ - प्रादेशिक राजधानी)',
    nameEnglish: 'Biratnagar (Morang - Province Capital)',
    province: 'कोशी प्रदेश',
    latitude: 26.4525,
    longitude: 87.2718,
    elevationMeters: 80,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sunsari_dharan',
    nameNepali: 'धरान (सुनसरी)',
    nameEnglish: 'Dharan (Sunsari)',
    province: 'कोशी प्रदेश',
    latitude: 26.8124,
    longitude: 87.2835,
    elevationMeters: 349,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sunsari_itahari',
    nameNepali: 'इटहरी (सुनसरी)',
    nameEnglish: 'Itahari (Sunsari)',
    province: 'कोशी प्रदेश',
    latitude: 26.6631,
    longitude: 87.2778,
    elevationMeters: 116,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sunsari_inaruwa',
    nameNepali: 'इनरुवा (सुनसरी सदरमुकाम)',
    nameEnglish: 'Inaruwa (Sunsari HQ)',
    province: 'कोशी प्रदेश',
    latitude: 26.6000,
    longitude: 87.1500,
    elevationMeters: 75,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'jhapa_birtamod',
    nameNepali: 'विर्तामोड / भद्रपुर (झापा)',
    nameEnglish: 'Birtamod / Bhadrapur (Jhapa)',
    province: 'कोशी प्रदेश',
    latitude: 26.6333,
    longitude: 87.9833,
    elevationMeters: 90,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'jhapa_damak',
    nameNepali: 'दमक (झापा)',
    nameEnglish: 'Damak (Jhapa)',
    province: 'कोशी प्रदेश',
    latitude: 26.6667,
    longitude: 87.7000,
    elevationMeters: 110,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'ilam',
    nameNepali: 'इलाम (चिया नगरी)',
    nameEnglish: 'Ilam',
    province: 'कोशी प्रदेश',
    latitude: 26.9111,
    longitude: 87.9264,
    elevationMeters: 1208,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'panchthar_phidim',
    nameNepali: 'पाँचथर (फिदिम)',
    nameEnglish: 'Panchthar (Phidim)',
    province: 'कोशी प्रदेश',
    latitude: 27.1500,
    longitude: 87.7667,
    elevationMeters: 1158,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'taplejung_fungling',
    nameNepali: 'ताप्लेजुङ (फुङलिङ / पाथिभरा)',
    nameEnglish: 'Taplejung (Fungling / Pathibhara)',
    province: 'कोशी प्रदेश',
    latitude: 27.3500,
    longitude: 87.6667,
    elevationMeters: 1820,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dhankuta',
    nameNepali: 'धनकुटा',
    nameEnglish: 'Dhankuta',
    province: 'कोशी प्रदेश',
    latitude: 26.9833,
    longitude: 87.3333,
    elevationMeters: 1200,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'tehrathum_myanglung',
    nameNepali: 'तेह्रथुम (म्याङ्लुङ)',
    nameEnglish: 'Tehrathum (Myanglung)',
    province: 'कोशी प्रदेश',
    latitude: 27.1500,
    longitude: 87.4333,
    elevationMeters: 1500,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sankhuwasabha_khandbari',
    nameNepali: 'सङ्खुवासभा (खाँदबारी)',
    nameEnglish: 'Sankhuwasabha (Khandbari)',
    province: 'कोशी प्रदेश',
    latitude: 27.3742,
    longitude: 87.2089,
    elevationMeters: 1060,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bhojpur',
    nameNepali: 'भोजपुर',
    nameEnglish: 'Bhojpur',
    province: 'कोशी प्रदेश',
    latitude: 27.1717,
    longitude: 87.0478,
    elevationMeters: 1540,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'solukhumbu_salleri',
    nameNepali: 'सोलुखुम्बु (सल्लेरी / नाम्चे)',
    nameEnglish: 'Solukhumbu (Salleri / Namche)',
    province: 'कोशी प्रदेश',
    latitude: 27.5000,
    longitude: 86.5833,
    elevationMeters: 2362,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'okhaldhunga',
    nameNepali: 'ओखलढुङ्गा (सिद्धचरण)',
    nameEnglish: 'Okhaldhunga (Siddhicharan)',
    province: 'कोशी प्रदेश',
    latitude: 27.3167,
    longitude: 86.5000,
    elevationMeters: 1561,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'khotang_diktel',
    nameNepali: 'खोटाङ (दिक्तेल / हलेसी)',
    nameEnglish: 'Khotang (Diktel / Halesi)',
    province: 'कोशी प्रदेश',
    latitude: 27.2167,
    longitude: 86.7833,
    elevationMeters: 1650,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'udayapur_gaighat',
    nameNepali: 'उदयपुर (गाईघाट / त्रियुगा)',
    nameEnglish: 'Udayapur (Gaighat / Triyuga)',
    province: 'कोशी प्रदेश',
    latitude: 26.7914,
    longitude: 86.7022,
    elevationMeters: 147,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 3. MADHESH PROVINCE (मधेश प्रदेश) - 8 Terai Districts
  // -------------------------------------------------------------
  {
    id: 'janakpur_dhanusha',
    nameNepali: 'जनकपुरधाम (धनुषा - प्रादेशिक राजधानी)',
    nameEnglish: 'Janakpurdham (Dhanusha - Province Capital)',
    province: 'मधेश प्रदेश',
    latitude: 26.7288,
    longitude: 85.9244,
    elevationMeters: 74,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'parsa_birgunj',
    nameNepali: 'वीरगञ्ज (पर्सा)',
    nameEnglish: 'Birgunj (Parsa)',
    province: 'मधेश प्रदेश',
    latitude: 27.0104,
    longitude: 84.8774,
    elevationMeters: 80,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'saptari_rajbiraj',
    nameNepali: 'सप्तरी (राजविराज)',
    nameEnglish: 'Saptari (Rajbiraj)',
    province: 'मधेश प्रदेश',
    latitude: 26.5414,
    longitude: 86.7533,
    elevationMeters: 76,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'siraha_lahan',
    nameNepali: 'सिराहा (लहान / सिराहा सदरमुकाम)',
    nameEnglish: 'Siraha (Lahan / Siraha HQ)',
    province: 'मधेश प्रदेश',
    latitude: 26.7258,
    longitude: 86.4897,
    elevationMeters: 90,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'mahottari_jaleshwar',
    nameNepali: 'महोत्तरी (जलेश्वर / बर्दिबास)',
    nameEnglish: 'Mahottari (Jaleshwar / Bardibas)',
    province: 'मधेश प्रदेश',
    latitude: 26.6433,
    longitude: 85.8019,
    elevationMeters: 62,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'sarlahi_malangwa',
    nameNepali: 'सर्लाही (मलङ्गवा / हरिवन)',
    nameEnglish: 'Sarlahi (Malangwa / Harion)',
    province: 'मधेश प्रदेश',
    latitude: 26.8569,
    longitude: 85.5583,
    elevationMeters: 79,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'rautahat_gaur',
    nameNepali: 'रौतहट (गौर / चन्द्रनिगाहपुर)',
    nameEnglish: 'Rautahat (Gaur / Chandranigahpur)',
    province: 'मधेश प्रदेश',
    latitude: 26.7644,
    longitude: 85.2778,
    elevationMeters: 81,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bara_kalaiya',
    nameNepali: 'बारा (कलैया / सिमरा)',
    nameEnglish: 'Bara (Kalaiya / Simara)',
    province: 'मधेश प्रदेश',
    latitude: 27.0306,
    longitude: 84.9750,
    elevationMeters: 85,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 4. GANDAKI PROVINCE (गण्डकी प्रदेश) - 11 Districts
  // -------------------------------------------------------------
  {
    id: 'kaski_pokhara',
    nameNepali: 'पोखरा (कास्की - प्रादेशिक राजधानी)',
    nameEnglish: 'Pokhara (Kaski - Province Capital)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.2096,
    longitude: 83.9856,
    elevationMeters: 822,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'tanahun_damauli',
    nameNepali: 'तनहुँ (दमौली / भीमाद)',
    nameEnglish: 'Tanahun (Damauli / Vyas)',
    province: 'गण्डकी प्रदेश',
    latitude: 27.9667,
    longitude: 84.2833,
    elevationMeters: 360,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'gorkha',
    nameNepali: 'गोरखा (गोरखा बजार / मनकामना)',
    nameEnglish: 'Gorkha (Gorkha / Manakamana)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.0000,
    longitude: 84.6333,
    elevationMeters: 1060,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'lamjung_besishahar',
    nameNepali: 'लमजुङ (बेसीशहर)',
    nameEnglish: 'Lamjung (Besishahar)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.2333,
    longitude: 84.3833,
    elevationMeters: 760,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'syangja_waling',
    nameNepali: 'स्याङ्जा (पुतलीबजार / वालिङ)',
    nameEnglish: 'Syangja (Putalibazar / Waling)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.0964,
    longitude: 83.8767,
    elevationMeters: 1088,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'parbat_kusma',
    nameNepali: 'पर्वत (कुश्मा / गुप्तेश्वर)',
    nameEnglish: 'Parbat (Kusma / Gupteshwar)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.2167,
    longitude: 83.6833,
    elevationMeters: 890,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'baglung',
    nameNepali: 'बागलुङ (बागलुङ कालिका)',
    nameEnglish: 'Baglung (Baglung Kalika)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.2667,
    longitude: 83.6000,
    elevationMeters: 1020,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'myagdi_beni',
    nameNepali: 'म्याग्दी (बेनी / गलेश्वर)',
    nameEnglish: 'Myagdi (Beni / Galeshwar)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.3444,
    longitude: 83.5639,
    elevationMeters: 899,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'mustang_jomsom',
    nameNepali: 'मुस्ताङ (जोमसोम / मुक्तिनाथ)',
    nameEnglish: 'Mustang (Jomsom / Muktinath)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.7806,
    longitude: 83.7250,
    elevationMeters: 2743,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'manang_chame',
    nameNepali: 'मनाङ (चामे / तिलिचो)',
    nameEnglish: 'Manang (Chame / Tilicho)',
    province: 'गण्डकी प्रदेश',
    latitude: 28.5500,
    longitude: 84.2333,
    elevationMeters: 2710,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'nawalpur_kawasoti',
    nameNepali: 'नवलपुर (कावासोती / गैँडाकोट)',
    nameEnglish: 'Nawalpur (Kawasoti / Gaindakot)',
    province: 'गण्डकी प्रदेश',
    latitude: 27.6500,
    longitude: 84.1333,
    elevationMeters: 160,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 5. LUMBINI PROVINCE (लुम्बिनी प्रदेश) - 12 Districts
  // -------------------------------------------------------------
  {
    id: 'rupandehi_butwal',
    nameNepali: 'बुटवल (रुपन्देही)',
    nameEnglish: 'Butwal (Rupandehi)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.7006,
    longitude: 83.4484,
    elevationMeters: 200,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'rupandehi_bhairahawa',
    nameNepali: 'भैरहवा / सिद्धार्थनगर (रुपन्देही)',
    nameEnglish: 'Bhairahawa / Siddharthanagar (Rupandehi)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.5061,
    longitude: 83.4506,
    elevationMeters: 104,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'rupandehi_lumbini',
    nameNepali: 'लुम्बिनी (भगवान् बुद्ध जन्मस्थल)',
    nameEnglish: 'Lumbini (Birthplace of Buddha)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.4833,
    longitude: 83.2750,
    elevationMeters: 98,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dang_ghorahi',
    nameNepali: 'दाङ (घोराही / देउखुरी - प्रादेशिक राजधानी)',
    nameEnglish: 'Dang (Ghorahi / Deukhuri - Province Capital)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.0500,
    longitude: 82.5000,
    elevationMeters: 600,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dang_tulsipur',
    nameNepali: 'तुलसीपुर (दाङ)',
    nameEnglish: 'Tulsipur (Dang)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.1333,
    longitude: 82.3000,
    elevationMeters: 670,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'banke_nepalgunj',
    nameNepali: 'नेपालगञ्ज / कोहलपुर (बाँके)',
    nameEnglish: 'Nepalgunj / Kohalpur (Banke)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.0500,
    longitude: 81.6167,
    elevationMeters: 150,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bardiya_gulariya',
    nameNepali: 'बर्दिया (गुलरिया / बाँसगढी)',
    nameEnglish: 'Bardiya (Gulariya / Bansgadhi)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.2333,
    longitude: 81.3333,
    elevationMeters: 142,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'kapilvastu_taulihawa',
    nameNepali: 'कपिलवस्तु (तौलिहवा / कृष्णनगर)',
    nameEnglish: 'Kapilvastu (Taulihawa / Krishnanagar)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.5500,
    longitude: 83.0500,
    elevationMeters: 107,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'palpa_tansen',
    nameNepali: 'पाल्पा (तानसेन)',
    nameEnglish: 'Palpa (Tansen)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.8667,
    longitude: 83.5500,
    elevationMeters: 1372,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'gulmi_tamghas',
    nameNepali: 'गुल्मी (तम्घास)',
    nameEnglish: 'Gulmi (Tamghas / Resunga)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.0667,
    longitude: 83.2500,
    elevationMeters: 1530,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'arghakhanchi_sandhikharka',
    nameNepali: 'अर्घाखाँची (सन्धिखर्क)',
    nameEnglish: 'Arghakhanchi (Sandhikharka)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.9833,
    longitude: 83.1500,
    elevationMeters: 1250,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'pyuthan_khalanga',
    nameNepali: 'प्युठान (खलङ्गा / विजुवार)',
    nameEnglish: 'Pyuthan (Khalanga / Bijuwar)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.1000,
    longitude: 82.8833,
    elevationMeters: 1340,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'rolpa_liwang',
    nameNepali: 'रोल्पा (लिवाङ)',
    nameEnglish: 'Rolpa (Liwang)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.3000,
    longitude: 82.6333,
    elevationMeters: 1350,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'parasi_ramgram',
    nameNepali: 'परासी (पश्चिम नवलपरासी / रामग्राम)',
    nameEnglish: 'Parasi (Nawalparasi West / Ramgram)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.5333,
    longitude: 83.6667,
    elevationMeters: 110,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'eastern_rukum_rukumkot',
    nameNepali: 'पूर्वी रुकुम (रुकुमकोट)',
    nameEnglish: 'Eastern Rukum (Rukumkot)',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.5833,
    longitude: 82.6333,
    elevationMeters: 1560,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 6. KARNALI PROVINCE (कर्णाली प्रदेश) - 10 Mountain Districts
  // -------------------------------------------------------------
  {
    id: 'surkhet_birendranagar',
    nameNepali: 'वीरेन्द्रनगर (सुर्खेत - प्रादेशिक राजधानी)',
    nameEnglish: 'Birendranagar (Surkhet - Province Capital)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.5833,
    longitude: 81.6333,
    elevationMeters: 665,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dailekh_narayan',
    nameNepali: 'दैलेख (नारायण / दुल्लु)',
    nameEnglish: 'Dailekh (Narayan / Dullu)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.8375,
    longitude: 81.7103,
    elevationMeters: 1448,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'jajarkot_khalanga',
    nameNepali: 'जाजरकोट (खलङ्गा)',
    nameEnglish: 'Jajarkot (Khalanga)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.7000,
    longitude: 82.2000,
    elevationMeters: 1225,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'salyan_khalanga',
    nameNepali: 'सल्यान (खलङ्गा / श्रीनगर)',
    nameEnglish: 'Salyan (Khalanga / Sreenagar)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.3667,
    longitude: 82.1667,
    elevationMeters: 1500,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'western_rukum_musikot',
    nameNepali: 'पश्चिम रुकुम (मुसिकोट)',
    nameEnglish: 'Western Rukum (Musikot)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.6333,
    longitude: 82.4833,
    elevationMeters: 1450,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'jumla_chandannath',
    nameNepali: 'जुम्ला (चन्दननाथ / खलङ्गा)',
    nameEnglish: 'Jumla (Chandannath / Khalanga)',
    province: 'कर्णाली प्रदेश',
    latitude: 29.2747,
    longitude: 82.1839,
    elevationMeters: 2514,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'kalikot_manma',
    nameNepali: 'कालिकोट (मान्म)',
    nameEnglish: 'Kalikot (Manma)',
    province: 'कर्णाली प्रदेश',
    latitude: 29.1333,
    longitude: 81.6000,
    elevationMeters: 1440,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'mugu_gamgadhi',
    nameNepali: 'मुगु (गमगढी / रारा ताल)',
    nameEnglish: 'Mugu (Gamgadhi / Rara Lake)',
    province: 'कर्णाली प्रदेश',
    latitude: 29.5500,
    longitude: 82.1667,
    elevationMeters: 2320,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'humla_simikot',
    nameNepali: 'हुम्ला (सिमिकोट)',
    nameEnglish: 'Humla (Simikot)',
    province: 'कर्णाली प्रदेश',
    latitude: 29.9667,
    longitude: 81.8333,
    elevationMeters: 2910,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dolpa_dunai',
    nameNepali: 'डोल्पा (दुनै / शे-फोक्सुण्डो)',
    nameEnglish: 'Dolpa (Dunai / Shey Phoksundo)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.9333,
    longitude: 82.9000,
    elevationMeters: 2092,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 7. SUDURPASHCHIM PROVINCE (सुदूरपश्चिम प्रदेश) - 9 Districts
  // -------------------------------------------------------------
  {
    id: 'kailali_dhangadhi',
    nameNepali: 'धनगढी (कैलाली - प्रादेशिक राजधानी)',
    nameEnglish: 'Dhangadhi (Kailali - Province Capital)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 28.6853,
    longitude: 80.5967,
    elevationMeters: 109,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'kailali_tikapur',
    nameNepali: 'टीकापुर (कैलाली)',
    nameEnglish: 'Tikapur (Kailali)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 28.5333,
    longitude: 81.1333,
    elevationMeters: 150,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'kanchanpur_mahendranagar',
    nameNepali: 'महेन्द्रनगर / भीमदत्त (कञ्चनपुर)',
    nameEnglish: 'Mahendranagar / Bhimdatta (Kanchanpur)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 28.9667,
    longitude: 80.1833,
    elevationMeters: 198,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dadeldhura_amargadhi',
    nameNepali: 'डडेल्धुरा (अमरगढी)',
    nameEnglish: 'Dadeldhura (Amargadhi)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.3000,
    longitude: 80.5833,
    elevationMeters: 1745,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'baitadi_dasharathchand',
    nameNepali: 'बैतडी (दशरथचन्द / पाटन)',
    nameEnglish: 'Baitadi (Dasharathchand / Patan)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.5333,
    longitude: 80.4667,
    elevationMeters: 1600,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'darchula_khalanga',
    nameNepali: 'दार्चुला (खलङ्गा / अपि हिमाल)',
    nameEnglish: 'Darchula (Khalanga / Api)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.8417,
    longitude: 80.5367,
    elevationMeters: 915,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'doti_silgadhi',
    nameNepali: 'डोटी (दिपायल सिलगढी)',
    nameEnglish: 'Doti (Dipayal Silgadhi)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.2667,
    longitude: 80.9667,
    elevationMeters: 1260,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'achham_mangalsen',
    nameNepali: 'अछाम (मङ्गलसेन / साँफेबगर)',
    nameEnglish: 'Achham (Mangalsen / Sanfebagar)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.1333,
    longitude: 81.2667,
    elevationMeters: 1370,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bajhang_chainpur',
    nameNepali: 'बझाङ (चैनपुर / साइपाल)',
    nameEnglish: 'Bajhang (Chainpur / Saipal)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.5667,
    longitude: 81.2000,
    elevationMeters: 1250,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bajura_martadi',
    nameNepali: 'बाजुरा (मार्तडी / बडीमालिका)',
    nameEnglish: 'Bajura (Martadi / Badimalika)',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 29.4500,
    longitude: 81.4833,
    elevationMeters: 1580,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },

  // -------------------------------------------------------------
  // 8. INTERNATIONAL NEPALI DIASPORA (अन्तर्राष्ट्रिय नेपाली समुदाय)
  // -------------------------------------------------------------
  {
    id: 'new_delhi',
    nameNepali: 'नयाँ दिल्ली (भारत)',
    nameEnglish: 'New Delhi (India)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 28.6139,
    longitude: 77.2090,
    elevationMeters: 216,
    timezone: 'Asia/Kolkata',
    timezoneOffsetMinutes: 330,
  },
  {
    id: 'sikkim_gangtok',
    nameNepali: 'गान्तोक (सिक्किम, भारत)',
    nameEnglish: 'Gangtok (Sikkim, India)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 27.3389,
    longitude: 88.6065,
    elevationMeters: 1650,
    timezone: 'Asia/Kolkata',
    timezoneOffsetMinutes: 330,
  },
  {
    id: 'darjeeling',
    nameNepali: 'दार्जिलिङ (भारत)',
    nameEnglish: 'Darjeeling (India)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 27.0410,
    longitude: 88.2663,
    elevationMeters: 2042,
    timezone: 'Asia/Kolkata',
    timezoneOffsetMinutes: 330,
  },
  {
    id: 'dubai',
    nameNepali: 'दुबई (युएई)',
    nameEnglish: 'Dubai (UAE)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 25.2048,
    longitude: 55.2708,
    elevationMeters: 16,
    timezone: 'Asia/Dubai',
    timezoneOffsetMinutes: 240,
  },
  {
    id: 'doha_qatar',
    nameNepali: 'दोहा (कतार)',
    nameEnglish: 'Doha (Qatar)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 25.2854,
    longitude: 51.5310,
    elevationMeters: 10,
    timezone: 'Asia/Qatar',
    timezoneOffsetMinutes: 180,
  },
  {
    id: 'riyadh_saudi',
    nameNepali: 'रियाद (साउदी अरब)',
    nameEnglish: 'Riyadh (Saudi Arabia)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 24.7136,
    longitude: 46.6753,
    elevationMeters: 612,
    timezone: 'Asia/Riyadh',
    timezoneOffsetMinutes: 180,
  },
  {
    id: 'kuala_lumpur',
    nameNepali: 'क्वालालम्पुर (मलेसिया)',
    nameEnglish: 'Kuala Lumpur (Malaysia)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 3.1390,
    longitude: 101.6869,
    elevationMeters: 66,
    timezone: 'Asia/Kuala_Lumpur',
    timezoneOffsetMinutes: 480,
  },
  {
    id: 'tokyo',
    nameNepali: 'टोकियो (जापान)',
    nameEnglish: 'Tokyo (Japan)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 35.6762,
    longitude: 139.6503,
    elevationMeters: 40,
    timezone: 'Asia/Tokyo',
    timezoneOffsetMinutes: 540,
  },
  {
    id: 'seoul',
    nameNepali: 'सियोल (दक्षिण कोरिया)',
    nameEnglish: 'Seoul (South Korea)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 37.5665,
    longitude: 126.9780,
    elevationMeters: 38,
    timezone: 'Asia/Seoul',
    timezoneOffsetMinutes: 540,
  },
  {
    id: 'sydney',
    nameNepali: 'सिड्नी (अस्ट्रेलिया)',
    nameEnglish: 'Sydney (Australia)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: -33.8688,
    longitude: 151.2093,
    elevationMeters: 19,
    timezone: 'Australia/Sydney',
    timezoneOffsetMinutes: 600,
  },
  {
    id: 'melbourne',
    nameNepali: 'मेलबर्न (अस्ट्रेलिया)',
    nameEnglish: 'Melbourne (Australia)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: -37.8136,
    longitude: 144.9631,
    elevationMeters: 31,
    timezone: 'Australia/Melbourne',
    timezoneOffsetMinutes: 600,
  },
  {
    id: 'london',
    nameNepali: 'लण्डन (संयुक्त अधिराज्य / UK)',
    nameEnglish: 'London (United Kingdom)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 51.5074,
    longitude: -0.1278,
    elevationMeters: 35,
    timezone: 'Europe/London',
    timezoneOffsetMinutes: 60,
  },
  {
    id: 'new_york',
    nameNepali: 'न्युयोर्क (अमेरिका)',
    nameEnglish: 'New York (USA)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 40.7128,
    longitude: -74.0060,
    elevationMeters: 10,
    timezone: 'America/New_York',
    timezoneOffsetMinutes: -300,
  },
  {
    id: 'dallas_texas',
    nameNepali: 'डल्लास, टेक्सास (अमेरिका)',
    nameEnglish: 'Dallas, Texas (USA)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 32.7767,
    longitude: -96.7970,
    elevationMeters: 131,
    timezone: 'America/Chicago',
    timezoneOffsetMinutes: -360,
  },
  {
    id: 'san_francisco',
    nameNepali: 'सान फ्रान्सिस्को (अमेरिका)',
    nameEnglish: 'San Francisco, California (USA)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 37.7749,
    longitude: -122.4194,
    elevationMeters: 16,
    timezone: 'America/Los_Angeles',
    timezoneOffsetMinutes: -480,
  },
  {
    id: 'toronto_canada',
    nameNepali: 'टोरन्टो (क्यानाडा)',
    nameEnglish: 'Toronto (Canada)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 43.6532,
    longitude: -79.3832,
    elevationMeters: 76,
    timezone: 'America/Toronto',
    timezoneOffsetMinutes: -300,
  },
];

export const DEFAULT_LOCATION = NEPAL_LOCATIONS[0]; // Kathmandu

export function getLocationById(id: string): LocationData {
  return NEPAL_LOCATIONS.find((loc) => loc.id === id) || DEFAULT_LOCATION;
}

/**
 * Finds the nearest location from GPS latitude & longitude using Haversine distance
 */
export function findNearestLocation(lat: number, lon: number): LocationData {
  let closestLoc = DEFAULT_LOCATION;
  let minDistance = Infinity;

  const toRad = (v: number) => (v * Math.PI) / 180;
  const R = 6371; // km

  for (const loc of NEPAL_LOCATIONS) {
    const dLat = toRad(loc.latitude - lat);
    const dLon = toRad(loc.longitude - lon);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(toRad(lat)) *
        Math.cos(toRad(loc.latitude)) *
        Math.sin(dLon / 2) *
        Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const distance = R * c;

    if (distance < minDistance) {
      minDistance = distance;
      closestLoc = loc;
    }
  }

  return closestLoc;
}
