import { LocationData } from '../types';

export const PROVINCES_NEPAL = [
  { id: 'p1', nameNepali: 'कोशी प्रदेश', nameEnglish: 'Koshi Province' },
  { id: 'p2', nameNepali: 'मधेश प्रदेश', nameEnglish: 'Madhesh Province' },
  { id: 'p3', nameNepali: 'बागमती प्रदेश', nameEnglish: 'Bagmati Province' },
  { id: 'p4', nameNepali: 'गण्डकी प्रदेश', nameEnglish: 'Gandaki Province' },
  { id: 'p5', nameNepali: 'लुम्बिनी प्रदेश', nameEnglish: 'Lumbini Province' },
  { id: 'p6', nameNepali: 'कर्णाली प्रदेश', nameEnglish: 'Karnali Province' },
  { id: 'p7', nameNepali: 'सुदूरपश्चिम प्रदेश', nameEnglish: 'Sudurpashchim Province' },
];

export const NEPAL_LOCATIONS: LocationData[] = [
  {
    id: 'kathmandu',
    nameNepali: 'काठमाडौँ (राजधानी)',
    nameEnglish: 'Kathmandu (Capital)',
    province: 'बागमती प्रदेश',
    latitude: 27.7172,
    longitude: 85.3240,
    elevationMeters: 1400,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345, // +5:45
    isDefault: true,
  },
  {
    id: 'pokhara',
    nameNepali: 'पोखरा',
    nameEnglish: 'Pokhara',
    province: 'गण्डकी प्रदेश',
    latitude: 28.2096,
    longitude: 83.9856,
    elevationMeters: 822,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'lalitpur',
    nameNepali: 'ललितपुर (पाटन)',
    nameEnglish: 'Lalitpur (Patan)',
    province: 'बागमती प्रदेश',
    latitude: 27.6710,
    longitude: 85.3218,
    elevationMeters: 1400,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bhaktapur',
    nameNepali: 'भक्तपुर',
    nameEnglish: 'Bhaktapur',
    province: 'बागमती प्रदेश',
    latitude: 27.6710,
    longitude: 85.4298,
    elevationMeters: 1401,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'biratnagar',
    nameNepali: 'विराटनगर',
    nameEnglish: 'Biratnagar',
    province: 'कोशी प्रदेश',
    latitude: 26.4525,
    longitude: 87.2718,
    elevationMeters: 80,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'birgunj',
    nameNepali: 'वीरगञ्ज',
    nameEnglish: 'Birgunj',
    province: 'मधेश प्रदेश',
    latitude: 27.0104,
    longitude: 84.8774,
    elevationMeters: 80,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dharan',
    nameNepali: 'धरान',
    nameEnglish: 'Dharan',
    province: 'कोशी प्रदेश',
    latitude: 26.8124,
    longitude: 87.2835,
    elevationMeters: 349,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'butwal',
    nameNepali: 'बुटवल',
    nameEnglish: 'Butwal',
    province: 'लुम्बिनी प्रदेश',
    latitude: 27.7006,
    longitude: 83.4484,
    elevationMeters: 200,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'janakpur',
    nameNepali: 'जनकपुरधाम',
    nameEnglish: 'Janakpurdham',
    province: 'मधेश प्रदेश',
    latitude: 26.7288,
    longitude: 85.9244,
    elevationMeters: 74,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'bharatpur',
    nameNepali: 'भरतपुर (चितवन)',
    nameEnglish: 'Bharatpur (Chitwan)',
    province: 'बागमती प्रदेश',
    latitude: 27.6833,
    longitude: 84.4333,
    elevationMeters: 208,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'nepalgunj',
    nameNepali: 'नेपालगञ्ज',
    nameEnglish: 'Nepalgunj',
    province: 'लुम्बिनी प्रदेश',
    latitude: 28.0500,
    longitude: 81.6167,
    elevationMeters: 150,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'dhangadhi',
    nameNepali: 'धनगढी',
    nameEnglish: 'Dhangadhi',
    province: 'सुदूरपश्चिम प्रदेश',
    latitude: 28.6853,
    longitude: 80.5967,
    elevationMeters: 109,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'surkhet',
    nameNepali: 'वीरेन्द्रनगर (सुर्खेत)',
    nameEnglish: 'Birendranagar (Surkhet)',
    province: 'कर्णाली प्रदेश',
    latitude: 28.5833,
    longitude: 81.6333,
    elevationMeters: 665,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  {
    id: 'hetauda',
    nameNepali: 'हेटौँडा',
    nameEnglish: 'Hetauda',
    province: 'बागमती प्रदेश',
    latitude: 27.4289,
    longitude: 85.0322,
    elevationMeters: 390,
    timezone: 'Asia/Kathmandu',
    timezoneOffsetMinutes: 345,
  },
  // International diaspora locations
  {
    id: 'new_york',
    nameNepali: 'न्युयोर्क (अमेरिका)',
    nameEnglish: 'New York (USA)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 40.7128,
    longitude: -74.0060,
    elevationMeters: 10,
    timezone: 'America/New_York',
    timezoneOffsetMinutes: -300, // EDT -240 / EST -300
  },
  {
    id: 'london',
    nameNepali: 'लण्डन (युके)',
    nameEnglish: 'London (UK)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 51.5074,
    longitude: -0.1278,
    elevationMeters: 35,
    timezone: 'Europe/London',
    timezoneOffsetMinutes: 60,
  },
  {
    id: 'sydney',
    nameNepali: 'सिड्नी (अस्ट्रेलिया)',
    nameEnglish: 'Sydney (Australia)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: -33.8688,
    longitude: 151.2093,
    elevationMeters: 19,
    timezone: 'Australia/Sydney',
    timezoneOffsetMinutes: 600,
  },
  {
    id: 'dubai',
    nameNepali: 'दुबई (युएई)',
    nameEnglish: 'Dubai (UAE)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 25.2048,
    longitude: 55.2708,
    elevationMeters: 16,
    timezone: 'Asia/Dubai',
    timezoneOffsetMinutes: 240,
  },
  {
    id: 'tokyo',
    nameNepali: 'टोकियो (जापान)',
    nameEnglish: 'Tokyo (Japan)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 35.6762,
    longitude: 139.6503,
    elevationMeters: 40,
    timezone: 'Asia/Tokyo',
    timezoneOffsetMinutes: 540,
  },
  {
    id: 'new_delhi',
    nameNepali: 'नयाँ दिल्ली (भारत)',
    nameEnglish: 'New Delhi (India)',
    province: 'अन्तर्राष्ट्रिय',
    latitude: 28.6139,
    longitude: 77.2090,
    elevationMeters: 216,
    timezone: 'Asia/Kolkata',
    timezoneOffsetMinutes: 330,
  },
];

export const DEFAULT_LOCATION = NEPAL_LOCATIONS[0]; // Kathmandu

export function getLocationById(id: string): LocationData {
  return NEPAL_LOCATIONS.find((loc) => loc.id === id) || DEFAULT_LOCATION;
}
